/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.custom.idea.management.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Idea service. Represents a row in the &quot;IdeaManagement_Idea&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.custom.idea.management.services.model.impl.IdeaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.custom.idea.management.services.model.impl.IdeaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Idea
 * @generated
 */
@ProviderType
public interface IdeaModel extends BaseModel<Idea>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a idea model instance should use the {@link Idea} interface instead.
	 */

	/**
	 * Returns the primary key of this idea.
	 *
	 * @return the primary key of this idea
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this idea.
	 *
	 * @param primaryKey the primary key of this idea
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the idea ID of this idea.
	 *
	 * @return the idea ID of this idea
	 */
	public long getIdeaId();

	/**
	 * Sets the idea ID of this idea.
	 *
	 * @param ideaId the idea ID of this idea
	 */
	public void setIdeaId(long ideaId);

	/**
	 * Returns the group ID of this idea.
	 *
	 * @return the group ID of this idea
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this idea.
	 *
	 * @param groupId the group ID of this idea
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this idea.
	 *
	 * @return the company ID of this idea
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this idea.
	 *
	 * @param companyId the company ID of this idea
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this idea.
	 *
	 * @return the user ID of this idea
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this idea.
	 *
	 * @param userId the user ID of this idea
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this idea.
	 *
	 * @return the user uuid of this idea
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this idea.
	 *
	 * @param userUuid the user uuid of this idea
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this idea.
	 *
	 * @return the user name of this idea
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this idea.
	 *
	 * @param userName the user name of this idea
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this idea.
	 *
	 * @return the create date of this idea
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this idea.
	 *
	 * @param createDate the create date of this idea
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this idea.
	 *
	 * @return the modified date of this idea
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this idea.
	 *
	 * @param modifiedDate the modified date of this idea
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this idea.
	 *
	 * @return the title of this idea
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this idea.
	 *
	 * @param title the title of this idea
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this idea.
	 *
	 * @return the description of this idea
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this idea.
	 *
	 * @param description the description of this idea
	 */
	public void setDescription(String description);

	/**
	 * Returns the content of this idea.
	 *
	 * @return the content of this idea
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this idea.
	 *
	 * @param content the content of this idea
	 */
	public void setContent(String content);

	@Override
	public Idea cloneWithOriginalValues();

}